// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: home_info.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           string                 `protobuf:"bytes,1,opt,name=all,proto3" json:"all,omitempty"`
	Urutan        string                 `protobuf:"bytes,2,opt,name=urutan,proto3" json:"urutan,omitempty"`
	Latin         string                 `protobuf:"bytes,3,opt,name=latin,proto3" json:"latin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointsInfo) Reset() {
	*x = EndpointsInfo{}
	mi := &file_home_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointsInfo) ProtoMessage() {}

func (x *EndpointsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_home_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointsInfo.ProtoReflect.Descriptor instead.
func (*EndpointsInfo) Descriptor() ([]byte, []int) {
	return file_home_info_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointsInfo) GetAll() string {
	if x != nil {
		return x.All
	}
	return ""
}

func (x *EndpointsInfo) GetUrutan() string {
	if x != nil {
		return x.Urutan
	}
	return ""
}

func (x *EndpointsInfo) GetLatin() string {
	if x != nil {
		return x.Latin
	}
	return ""
}

type HomeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Endpoints     *EndpointsInfo         `protobuf:"bytes,3,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeInfo) Reset() {
	*x = HomeInfo{}
	mi := &file_home_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeInfo) ProtoMessage() {}

func (x *HomeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_home_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeInfo.ProtoReflect.Descriptor instead.
func (*HomeInfo) Descriptor() ([]byte, []int) {
	return file_home_info_proto_rawDescGZIP(), []int{1}
}

func (x *HomeInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *HomeInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *HomeInfo) GetEndpoints() *EndpointsInfo {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_home_info_proto protoreflect.FileDescriptor

const file_home_info_proto_rawDesc = "" +
	"\n" +
	"\x0fhome_info.proto\x12\bentities\"O\n" +
	"\rEndpointsInfo\x12\x10\n" +
	"\x03all\x18\x01 \x01(\tR\x03all\x12\x16\n" +
	"\x06urutan\x18\x02 \x01(\tR\x06urutan\x12\x14\n" +
	"\x05latin\x18\x03 \x01(\tR\x05latin\"y\n" +
	"\bHomeInfo\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x125\n" +
	"\tendpoints\x18\x03 \x01(\v2\x17.entities.EndpointsInfoR\tendpointsB\x1bZ\x19asmaul-husna/pkg/entitiesb\x06proto3"

var (
	file_home_info_proto_rawDescOnce sync.Once
	file_home_info_proto_rawDescData []byte
)

func file_home_info_proto_rawDescGZIP() []byte {
	file_home_info_proto_rawDescOnce.Do(func() {
		file_home_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_home_info_proto_rawDesc), len(file_home_info_proto_rawDesc)))
	})
	return file_home_info_proto_rawDescData
}

var file_home_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_home_info_proto_goTypes = []any{
	(*EndpointsInfo)(nil), // 0: entities.EndpointsInfo
	(*HomeInfo)(nil),      // 1: entities.HomeInfo
}
var file_home_info_proto_depIdxs = []int32{
	0, // 0: entities.HomeInfo.endpoints:type_name -> entities.EndpointsInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_home_info_proto_init() }
func file_home_info_proto_init() {
	if File_home_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_home_info_proto_rawDesc), len(file_home_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_home_info_proto_goTypes,
		DependencyIndexes: file_home_info_proto_depIdxs,
		MessageInfos:      file_home_info_proto_msgTypes,
	}.Build()
	File_home_info_proto = out.File
	file_home_info_proto_goTypes = nil
	file_home_info_proto_depIdxs = nil
}
