package utils

import (
	"asmaul-husna/pkg/entities"
)

// An utility function to load Asma'ul Husna
func LoadAsmaulHusnaData() ([]entities.AsmaulHusna, error) {
	var data []entities.AsmaulHusna = []entities.AsmaulHusna{
		{
			Urutan: 1,
			Latin:  "Ar Rahman",
			Arab:   "الرحمن",
			Arti:   "Yang Maha Pengasih",
		},
		{
			Urutan: 2,
			Latin:  "Ar Rahiim",
			Arab:   "الرحيم",
			Arti:   "Yang Maha Penyayang",
		},
		{
			Urutan: 3,
			Latin:  "Al Malik",
			Arab:   "الملك",
			Arti:   "Yang Maha Merajai / Memerintah",
		},
		{
			Urutan: 4,
			Latin:  "Al Quddus",
			Arab:   "القدوس",
			Arti:   "Yang Maha Suci",
		},
		{
			Urutan: 5,
			Latin:  "As Salaam",
			Arab:   "السلام",
			Arti:   "Yang Maha Memberi Kesejahteraan",
		},
		{
			Urutan: 6,
			Latin:  "Al Mu 'min",
			Arab:   "المؤمن",
			Arti:   "Yang Maha Memberi Keamanan",
		},
		{
			Urutan: 7,
			Latin:  "Al Muhaimin",
			Arab:   "المهيمن",
			Arti:   "Yang Maha Pemelihara",
		},
		{
			Urutan: 8,
			Latin:  "Al 'Aziiz",
			Arab:   "العزيز",
			Arti:   "Yang Maha Perkasa",
		},
		{
			Urutan: 9,
			Latin:  "Al Jabbar",
			Arab:   "الجبار",
			Arti:   "Yang Memiliki Mutlak Kegagahan",
		},
		{
			Urutan: 10,
			Latin:  "Al Mutakabbir",
			Arab:   "المتكبر",
			Arti:   "Yang Maha Megah, Yang Memiliki Kebesaran",
		},
		{
			Urutan: 11,
			Latin:  "Al Khaliq",
			Arab:   "الخالق",
			Arti:   "Yang Maha Pencipta",
		},
		{
			Urutan: 12,
			Latin:  "Al Baari '",
			Arab:   "البارئ",
			Arti:   "Yang Maha Melepaskan(Membuat, Membentuk, Menyeimbangkan)",
		},
		{
			Urutan: 13,
			Latin:  "Al Mushawwir",
			Arab:   "المصور",
			Arti:   "Yang Maha Membentuk Rupa(makhluknya)",
		},
		{
			Urutan: 14,
			Latin:  "Al Ghaffaar",
			Arab:   "الغفار",
			Arti:   "Yang Maha Pengampun",
		},
		{
			Urutan: 15,
			Latin:  "Al Qahhaar",
			Arab:   "القهار",
			Arti:   "Yang Maha Memaksa",
		},
		{
			Urutan: 16,
			Latin:  "Al Wahhaab",
			Arab:   "الوهاب",
			Arti:   "Yang Maha Pemberi Karunia",
		},
		{
			Urutan: 17,
			Latin:  "Ar Razzaaq",
			Arab:   "الرزاق",
			Arti:   "Yang Maha Pemberi Rezeki",
		},
		{
			Urutan: 18,
			Latin:  "Al Fattaah",
			Arab:   "الفتاح",
			Arti:   "Yang Maha Pembuka Rahmat",
		},
		{
			Urutan: 19,
			Latin:  "Al 'Aliim",
			Arab:   "العليم",
			Arti:   "Yang Maha Mengetahui(Memiliki Ilmu)",
		},
		{
			Urutan: 20,
			Latin:  "Al Qaabidh",
			Arab:   "القابض",
			Arti:   "Yang Maha Menyempitkan(makhluknya)",
		},
		{
			Urutan: 21,
			Latin:  "Al Baasith",
			Arab:   "الباسط",
			Arti:   "Yang Maha Melapangkan(makhluknya)",
		},
		{
			Urutan: 22,
			Latin:  "Al Khaafidh",
			Arab:   "الخافض",
			Arti:   "Yang Maha Merendahkan(makhluknya)",
		},
		{
			Urutan: 23,
			Latin:  "Ar Raafi '",
			Arab:   "الرافع",
			Arti:   "Yang Maha Meninggikan(makhluknya)",
		},
		{
			Urutan: 24,
			Latin:  "Al Mu'izz",
			Arab:   "المعز",
			Arti:   "Yang Maha Memuliakan(makhluknya)",
		},
		{
			Urutan: 25,
			Latin:  "Al Mudzil",
			Arab:   "المذل",
			Arti:   "Yang Maha Menghinakan(makhluknya)",
		},
		{
			Urutan: 26,
			Latin:  "Al Samii '",
			Arab:   "السميع",
			Arti:   "Yang Maha Mendengar",
		},
		{
			Urutan: 27,
			Latin:  "Al Bashiir",
			Arab:   "البصير",
			Arti:   "Yang Maha Melihat",
		},
		{
			Urutan: 28,
			Latin:  "Al Hakam",
			Arab:   "الحكم",
			Arti:   "Yang Maha Menetapkan",
		},
		{
			Urutan: 29,
			Latin:  "Al 'Adl",
			Arab:   "العدل",
			Arti:   "Yang Maha Adil",
		},
		{
			Urutan: 30,
			Latin:  "Al Lathiif",
			Arab:   "اللطيف",
			Arti:   "Yang Maha Lembut",
		},
		{
			Urutan: 31,
			Latin:  "Al Khabiir",
			Arab:   "الخبير",
			Arti:   "Yang Maha Mengenal",
		},
		{
			Urutan: 32,
			Latin:  "Al Haliim",
			Arab:   "الحليم",
			Arti:   "Yang Maha Penyantun",
		},
		{
			Urutan: 33,
			Latin:  "Al 'Azhiim",
			Arab:   "العظيم",
			Arti:   "Yang Maha Agung",
		},
		{
			Urutan: 34,
			Latin:  "Al Ghafuur",
			Arab:   "الغفور",
			Arti:   "Yang Maha Pengampun",
		},
		{
			Urutan: 35,
			Latin:  "As Syakuur",
			Arab:   "الشكور",
			Arti:   "Yang Maha Pembalas Budi(Menghargai)",
		},
		{
			Urutan: 36,
			Latin:  "Al 'Aliy",
			Arab:   "العلى",
			Arti:   "Yang Maha Tinggi",
		},
		{
			Urutan: 37,
			Latin:  "Al Kabiir",
			Arab:   "الكبير",
			Arti:   "Yang Maha Besar",
		},
		{
			Urutan: 38,
			Latin:  "Al Hafizh",
			Arab:   "الحفيظ",
			Arti:   "Yang Maha Memelihara",
		},
		{
			Urutan: 39,
			Latin:  "Al Muqiit",
			Arab:   "المقيت",
			Arti:   "Yang Maha Pemberi Kecukupan",
		},
		{
			Urutan: 40,
			Latin:  "Al Hasiib",
			Arab:   "الحسيب",
			Arti:   "Yang Maha Membuat Perhitungan",
		},
		{
			Urutan: 41,
			Latin:  "Al Jaliil",
			Arab:   "الجليل",
			Arti:   "Yang Maha Mulia",
		},
		{
			Urutan: 42,
			Latin:  "Al Kariim",
			Arab:   "الكريم",
			Arti:   "Yang Maha Mulia",
		},
		{
			Urutan: 43,
			Latin:  "Ar Raqiib",
			Arab:   "الرقيب",
			Arti:   "Yang Maha Mengawasi",
		},
		{
			Urutan: 44,
			Latin:  "Al Mujiib",
			Arab:   "المجيب",
			Arti:   "Yang Maha Mengabulkan",
		},
		{
			Urutan: 45,
			Latin:  "Al Waasi '",
			Arab:   "الواسع",
			Arti:   "Yang Maha Luas",
		},
		{
			Urutan: 46,
			Latin:  "Al Hakiim",
			Arab:   "الحكيم",
			Arti:   "Yang Maha Maka Bijaksana",
		},
		{
			Urutan: 47,
			Latin:  "Al Waduud",
			Arab:   "الودود",
			Arti:   "Yang Maha Mengasihi",
		},
		{
			Urutan: 48,
			Latin:  "Al Majiid",
			Arab:   "المجيد",
			Arti:   "Yang Maha Mulia",
		},
		{
			Urutan: 49,
			Latin:  "Al Baa'its",
			Arab:   "الباعث",
			Arti:   "Yang Maha Membangkitkan",
		},
		{
			Urutan: 50,
			Latin:  "As Syahiid",
			Arab:   "الشهيد",
			Arti:   "Yang Maha Menyaksikan",
		},
		{
			Urutan: 51,
			Latin:  "Al Haqq",
			Arab:   "الحق",
			Arti:   "Yang Maha Benar",
		},
		{
			Urutan: 52,
			Latin:  "Al Wakiil",
			Arab:   "الوكيل",
			Arti:   "Yang Maha Memelihara",
		},
		{
			Urutan: 53,
			Latin:  "Al Qawiyyu",
			Arab:   "القوى",
			Arti:   "Yang Maha Kuat",
		},
		{
			Urutan: 54,
			Latin:  "Al Matiin",
			Arab:   "المتين",
			Arti:   "Yang Maha Kokoh",
		},
		{
			Urutan: 55,
			Latin:  "Al Waliyy",
			Arab:   "الولى",
			Arti:   "Yang Maha Melindungi",
		},
		{
			Urutan: 56,
			Latin:  "Al Hamiid",
			Arab:   "الحميد",
			Arti:   "Yang Maha Terpuji",
		},
		{
			Urutan: 57,
			Latin:  "Al Muhshii",
			Arab:   "المحصى",
			Arti:   "Yang Maha Mengalkulasi(Menghitung Segala Sesuatu)",
		},
		{
			Urutan: 58,
			Latin:  "Al Mubdi '",
			Arab:   "المبدئ",
			Arti:   "Yang Maha Memulai",
		},
		{
			Urutan: 59,
			Latin:  "Al Mu'iid",
			Arab:   "المعيد",
			Arti:   "Yang Maha Mengembalikan Kehidupan",
		},
		{
			Urutan: 60,
			Latin:  "Al Muhyii",
			Arab:   "المحيى",
			Arti:   "Yang Maha Menghidupkan",
		},
		{
			Urutan: 61,
			Latin:  "Al Mumiitu",
			Arab:   "المميت",
			Arti:   "Yang Maha Mematikan",
		},
		{
			Urutan: 62,
			Latin:  "Al Hayyu",
			Arab:   "الحي",
			Arti:   "Yang Maha Hidup",
		},
		{
			Urutan: 63,
			Latin:  "Al Qayyuum",
			Arab:   "القيوم",
			Arti:   "Yang Maha Mandiri",
		},
		{
			Urutan: 64,
			Latin:  "Al Waajid",
			Arab:   "الواجد",
			Arti:   "Yang Maha Penemu",
		},
		{
			Urutan: 65,
			Latin:  "Al Maajid",
			Arab:   "الماجد",
			Arti:   "Yang Maha Mulia",
		},
		{
			Urutan: 66,
			Latin:  "Al Wahiid",
			Arab:   "الواحد",
			Arti:   "Yang Maha Tunggal",
		},
		{
			Urutan: 67,
			Latin:  "Al Ahad",
			Arab:   "الاحد",
			Arti:   "Yang Maha Esa",
		},
		{
			Urutan: 68,
			Latin:  "As Shamad",
			Arab:   "الصمد",
			Arti:   "Yang Maha Dibutuhkan, Tempat Meminta",
		}, {
			Urutan: 69,
			Latin:  "Al Qaadir",
			Arab:   "القادر",
			Arti:   "Yang Maha Menentukan, Maha Menyeimbangkan",
		},
		{
			Urutan: 70,
			Latin:  "Al Muqtadir",
			Arab:   "المقتدر",
			Arti:   "Yang Maha Berkuasa",
		},
		{
			Urutan: 71,
			Latin:  "Al Muqaddim",
			Arab:   "المقدم",
			Arti:   "Yang Maha Mendahulukan",
		},
		{
			Urutan: 72,
			Latin:  "Al Mu 'akkhir",
			Arab:   "المؤخر",
			Arti:   "Yang Maha Mengakhirkan",
		},
		{
			Urutan: 73,
			Latin:  "Al Awwal",
			Arab:   "الأول",
			Arti:   "Yang Maha Awal",
		},
		{
			Urutan: 74,
			Latin:  "Al Aakhir",
			Arab:   "الأخر",
			Arti:   "Yang Maha Akhir",
		},
		{
			Urutan: 75,
			Latin:  "Az Zhaahir",
			Arab:   "الظاهر",
			Arti:   "Yang Maha Nyata",
		},
		{
			Urutan: 76,
			Latin:  "Al Baathin",
			Arab:   "الباطن",
			Arti:   "Yang Maha Ghaib",
		},
		{
			Urutan: 77,
			Latin:  "Al Waali",
			Arab:   "الوالي",
			Arti:   "Yang Maha Memerintah",
		},
		{
			Urutan: 78,
			Latin:  "Al Muta'aalii",
			Arab:   "المتعالي",
			Arti:   "Yang Maha Tinggi",
		},
		{
			Urutan: 79,
			Latin:  "Al Barru",
			Arab:   "البر",
			Arti:   "Yang Maha Penderma(Maha Pemberi Kebajikan)",
		},
		{
			Urutan: 80,
			Latin:  "At Tawwaab",
			Arab:   "التواب",
			Arti:   "Yang Maha Penerima Tobat",
		},
		{
			Urutan: 81,
			Latin:  "Al Muntaqim",
			Arab:   "المنتقم",
			Arti:   "Yang Maha Pemberi Balasan",
		},
		{
			Urutan: 82,
			Latin:  "Al Afuww",
			Arab:   "العفو",
			Arti:   "Yang Maha Pemaaf",
		},
		{
			Urutan: 83,
			Latin:  "Ar Ra 'uuf",
			Arab:   "الرؤوف",
			Arti:   "Yang Maha Pengasuh",
		},
		{
			Urutan: 84,
			Latin:  "Malikul Mulk",
			Arab:   "مالك الملك",
			Arti:   "Yang Maha Penguasa Kerajaan(Semesta)",
		},
		{
			Urutan: 85,
			Latin:  "Dzul Jalaali Wal Ikraam",
			Arab:   "ذو الجلال و الإكرام",
			Arti:   "Yang Maha Pemilik Kebesaran dan Kemuliaan",
		},
		{
			Urutan: 86,
			Latin:  "Al Muqsith",
			Arab:   "المقسط",
			Arti:   "Yang Maha Pemberi Keadilan",
		},
		{
			Urutan: 87,
			Latin:  "Al Jamii'",
			Arab:   "الجامع",
			Arti:   "Yang Maha Mengumpulkan",
		},
		{
			Urutan: 88,
			Latin:  "Al Ghaniyy",
			Arab:   "الغنى",
			Arti:   "Yang Maha Kaya",
		},
		{
			Urutan: 89,
			Latin:  "Al Mughnii",
			Arab:   "المغنى",
			Arti:   "Yang Maha Pemberi Kekayaan",
		},
		{
			Urutan: 90,
			Latin:  "Al Maani",
			Arab:   "المانع",
			Arti:   "Yang Maha Mencegah",
		},
		{
			Urutan: 91,
			Latin:  "Ad Dhaar",
			Arab:   "الضار",
			Arti:   "Yang Maha Penimpa Kemudharatan",
		},
		{
			Urutan: 92,
			Latin:  "An Nafii '",
			Arab:   "النافع",
			Arti:   "Yang Maha Memberi Manfaat",
		},
		{
			Urutan: 93,
			Latin:  "An Nuur",
			Arab:   "النور",
			Arti:   "Yang Maha Bercahaya(Menerangi, Memberi Cahaya)",
		},
		{
			Urutan: 94,
			Latin:  "Al Haadii",
			Arab:   "الهادئ",
			Arti:   "Yang Maha Pemberi Petunjuk",
		},
		{
			Urutan: 95,
			Latin:  "Al Badii'",
			Arab:   "البديع",
			Arti:   "Yang Maha Pencipta Yang Tiada Bandingannya",
		},
		{
			Urutan: 96,
			Latin:  "Al Baaqii",
			Arab:   "الباقي",
			Arti:   "Yang Maha Kekal",
		},
		{
			Urutan: 97,
			Latin:  "Al Waarits",
			Arab:   "الوارث",
			Arti:   "Yang Maha Pewaris",
		},
		{
			Urutan: 98,
			Latin:  "Ar Rasyiid",
			Arab:   "الرشيد",
			Arti:   "Yang Maha Pandai",
		},
		{
			Urutan: 99,
			Latin:  "As Shabuur",
			Arab:   "الصبور",
			Arti:   "Yang Maha Sabar",
		},
	}

	return data, nil
}
