FROM golang:1.25.1-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download && go mod verify && go mod tidy

COPY . ./

EXPOSE 5000

CMD ["air", "-c", ".air.toml"]