version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asmaul-husna-api
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VERCEL_DOCKER_TOKEN=${VERCEL_DOCKER_TOKEN}
