version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asmaul-husna-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/nestjs/node_modules
