// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/models/responses/asmaul_husna_response.proto

package responses

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsmaulHusna struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urutan        int32                  `protobuf:"varint,1,opt,name=urutan,proto3" json:"urutan,omitempty"`
	Latin         string                 `protobuf:"bytes,2,opt,name=latin,proto3" json:"latin,omitempty"`
	Arab          string                 `protobuf:"bytes,3,opt,name=arab,proto3" json:"arab,omitempty"`
	Arti          string                 `protobuf:"bytes,4,opt,name=arti,proto3" json:"arti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsmaulHusna) Reset() {
	*x = AsmaulHusna{}
	mi := &file_pkg_models_responses_asmaul_husna_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsmaulHusna) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsmaulHusna) ProtoMessage() {}

func (x *AsmaulHusna) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_responses_asmaul_husna_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsmaulHusna.ProtoReflect.Descriptor instead.
func (*AsmaulHusna) Descriptor() ([]byte, []int) {
	return file_pkg_models_responses_asmaul_husna_response_proto_rawDescGZIP(), []int{0}
}

func (x *AsmaulHusna) GetUrutan() int32 {
	if x != nil {
		return x.Urutan
	}
	return 0
}

func (x *AsmaulHusna) GetLatin() string {
	if x != nil {
		return x.Latin
	}
	return ""
}

func (x *AsmaulHusna) GetArab() string {
	if x != nil {
		return x.Arab
	}
	return ""
}

func (x *AsmaulHusna) GetArti() string {
	if x != nil {
		return x.Arti
	}
	return ""
}

var File_pkg_models_responses_asmaul_husna_response_proto protoreflect.FileDescriptor

const file_pkg_models_responses_asmaul_husna_response_proto_rawDesc = "" +
	"\n" +
	"0pkg/models/responses/asmaul_husna_response.proto\x12\tresponses\"c\n" +
	"\vAsmaulHusna\x12\x16\n" +
	"\x06urutan\x18\x01 \x01(\x05R\x06urutan\x12\x14\n" +
	"\x05latin\x18\x02 \x01(\tR\x05latin\x12\x12\n" +
	"\x04arab\x18\x03 \x01(\tR\x04arab\x12\x12\n" +
	"\x04arti\x18\x04 \x01(\tR\x04artiB#Z!asmaul-husna/pkg/models/responsesb\x06proto3"

var (
	file_pkg_models_responses_asmaul_husna_response_proto_rawDescOnce sync.Once
	file_pkg_models_responses_asmaul_husna_response_proto_rawDescData []byte
)

func file_pkg_models_responses_asmaul_husna_response_proto_rawDescGZIP() []byte {
	file_pkg_models_responses_asmaul_husna_response_proto_rawDescOnce.Do(func() {
		file_pkg_models_responses_asmaul_husna_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_models_responses_asmaul_husna_response_proto_rawDesc), len(file_pkg_models_responses_asmaul_husna_response_proto_rawDesc)))
	})
	return file_pkg_models_responses_asmaul_husna_response_proto_rawDescData
}

var file_pkg_models_responses_asmaul_husna_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_models_responses_asmaul_husna_response_proto_goTypes = []any{
	(*AsmaulHusna)(nil), // 0: responses.AsmaulHusna
}
var file_pkg_models_responses_asmaul_husna_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_models_responses_asmaul_husna_response_proto_init() }
func file_pkg_models_responses_asmaul_husna_response_proto_init() {
	if File_pkg_models_responses_asmaul_husna_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_models_responses_asmaul_husna_response_proto_rawDesc), len(file_pkg_models_responses_asmaul_husna_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_models_responses_asmaul_husna_response_proto_goTypes,
		DependencyIndexes: file_pkg_models_responses_asmaul_husna_response_proto_depIdxs,
		MessageInfos:      file_pkg_models_responses_asmaul_husna_response_proto_msgTypes,
	}.Build()
	File_pkg_models_responses_asmaul_husna_response_proto = out.File
	file_pkg_models_responses_asmaul_husna_response_proto_goTypes = nil
	file_pkg_models_responses_asmaul_husna_response_proto_depIdxs = nil
}
