// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/models/response.proto

package models

import (
	generated "asmaul-husna/pkg/entities/generated"
	responses "asmaul-husna/pkg/models/responses"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stack         string                 `protobuf:"bytes,3,opt,name=stack,proto3" json:"stack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIErrorResponse) Reset() {
	*x = APIErrorResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIErrorResponse) ProtoMessage() {}

func (x *APIErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIErrorResponse.ProtoReflect.Descriptor instead.
func (*APIErrorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{0}
}

func (x *APIErrorResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APIErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIErrorResponse) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

type APISuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Data          *responses.AsmaulHusna `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISuccessResponse) Reset() {
	*x = APISuccessResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISuccessResponse) ProtoMessage() {}

func (x *APISuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISuccessResponse.ProtoReflect.Descriptor instead.
func (*APISuccessResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{1}
}

func (x *APISuccessResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APISuccessResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *APISuccessResponse) GetData() *responses.AsmaulHusna {
	if x != nil {
		return x.Data
	}
	return nil
}

type APISuccessResponseAllAsmaulHusna struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StatusCode    int32                     `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Total         int32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Data          *responses.AllAsmaulHusna `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISuccessResponseAllAsmaulHusna) Reset() {
	*x = APISuccessResponseAllAsmaulHusna{}
	mi := &file_pkg_models_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISuccessResponseAllAsmaulHusna) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISuccessResponseAllAsmaulHusna) ProtoMessage() {}

func (x *APISuccessResponseAllAsmaulHusna) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISuccessResponseAllAsmaulHusna.ProtoReflect.Descriptor instead.
func (*APISuccessResponseAllAsmaulHusna) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{2}
}

func (x *APISuccessResponseAllAsmaulHusna) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APISuccessResponseAllAsmaulHusna) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *APISuccessResponseAllAsmaulHusna) GetData() *responses.AllAsmaulHusna {
	if x != nil {
		return x.Data
	}
	return nil
}

type APIInfoResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Author        string                   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Repository    string                   `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Endpoints     *generated.EndpointsInfo `protobuf:"bytes,3,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIInfoResponse) Reset() {
	*x = APIInfoResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIInfoResponse) ProtoMessage() {}

func (x *APIInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIInfoResponse.ProtoReflect.Descriptor instead.
func (*APIInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{3}
}

func (x *APIInfoResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *APIInfoResponse) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *APIInfoResponse) GetEndpoints() *generated.EndpointsInfo {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_pkg_models_response_proto protoreflect.FileDescriptor

const file_pkg_models_response_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/models/response.proto\x12\x06models\x1a\"pkg/entities/proto/home_info.proto\x1a0pkg/models/responses/asmaul_husna_response.proto\"b\n" +
	"\x10APIErrorResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05stack\x18\x03 \x01(\tR\x05stack\"v\n" +
	"\x12APISuccessResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.responses.AsmaulHusnaR\x04data\"\x87\x01\n" +
	" APISuccessResponseAllAsmaulHusna\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.responses.AllAsmaulHusnaR\x04data\"\x80\x01\n" +
	"\x0fAPIInfoResponse\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x125\n" +
	"\tendpoints\x18\x03 \x01(\v2\x17.entities.EndpointsInfoR\tendpointsB\x19Z\x17asmaul-husna/pkg/modelsb\x06proto3"

var (
	file_pkg_models_response_proto_rawDescOnce sync.Once
	file_pkg_models_response_proto_rawDescData []byte
)

func file_pkg_models_response_proto_rawDescGZIP() []byte {
	file_pkg_models_response_proto_rawDescOnce.Do(func() {
		file_pkg_models_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_models_response_proto_rawDesc), len(file_pkg_models_response_proto_rawDesc)))
	})
	return file_pkg_models_response_proto_rawDescData
}

var file_pkg_models_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_models_response_proto_goTypes = []any{
	(*APIErrorResponse)(nil),                 // 0: models.APIErrorResponse
	(*APISuccessResponse)(nil),               // 1: models.APISuccessResponse
	(*APISuccessResponseAllAsmaulHusna)(nil), // 2: models.APISuccessResponseAllAsmaulHusna
	(*APIInfoResponse)(nil),                  // 3: models.APIInfoResponse
	(*responses.AsmaulHusna)(nil),            // 4: responses.AsmaulHusna
	(*responses.AllAsmaulHusna)(nil),         // 5: responses.AllAsmaulHusna
	(*generated.EndpointsInfo)(nil),          // 6: entities.EndpointsInfo
}
var file_pkg_models_response_proto_depIdxs = []int32{
	4, // 0: models.APISuccessResponse.data:type_name -> responses.AsmaulHusna
	5, // 1: models.APISuccessResponseAllAsmaulHusna.data:type_name -> responses.AllAsmaulHusna
	6, // 2: models.APIInfoResponse.endpoints:type_name -> entities.EndpointsInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_models_response_proto_init() }
func file_pkg_models_response_proto_init() {
	if File_pkg_models_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_models_response_proto_rawDesc), len(file_pkg_models_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_models_response_proto_goTypes,
		DependencyIndexes: file_pkg_models_response_proto_depIdxs,
		MessageInfos:      file_pkg_models_response_proto_msgTypes,
	}.Build()
	File_pkg_models_response_proto = out.File
	file_pkg_models_response_proto_goTypes = nil
	file_pkg_models_response_proto_depIdxs = nil
}
