// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Get Info about the API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AsmaulHusna"
                ],
                "summary": "Get Info about the API",
                "responses": {
                    "200": {
                        "description": "Get Info success!",
                        "schema": {
                            "$ref": "#/definitions/models.APIInfoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/all": {
            "get": {
                "description": "Get all Asma'ul Husna with optional query page and limit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AsmaulHusna"
                ],
                "summary": "Get all Asma'ul Husna with optional query page and limit",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Asma'ul Husna success!",
                        "schema": {
                            "$ref": "#/definitions/models.APISuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/latin/{latin}": {
            "get": {
                "description": "Get Asma'ul Husna based on latin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AsmaulHusna"
                ],
                "summary": "Get Asma'ul Husna based on latin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Latin",
                        "name": "latin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Asma'ul Husna based on latin success!",
                        "schema": {
                            "$ref": "#/definitions/models.APISuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{urutan}": {
            "get": {
                "description": "Get Asma'ul Husna based on urutan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AsmaulHusna"
                ],
                "summary": "Get Asma'ul Husna based on urutan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Urutan",
                        "name": "urutan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Asma'ul Husna based on urutan success!",
                        "schema": {
                            "$ref": "#/definitions/models.APISuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APISuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get Metrics",
                "responses": {
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.EndpointsInfo": {
            "type": "object",
            "properties": {
                "all": {
                    "type": "string"
                },
                "latin": {
                    "type": "string"
                },
                "urutan": {
                    "type": "string"
                }
            }
        },
        "models.APIErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "stack": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "models.APIInfoResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "endpoints": {
                    "$ref": "#/definitions/entities.EndpointsInfo"
                },
                "repository": {
                    "type": "string"
                }
            }
        },
        "models.APISuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/responses.AsmaulHusna"
                },
                "statusCode": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "responses.AsmaulHusna": {
            "type": "object",
            "properties": {
                "arab": {
                    "type": "string"
                },
                "arti": {
                    "type": "string"
                },
                "latin": {
                    "type": "string"
                },
                "urutan": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter the token with the ` + "`" + `Bearer ` + "`" + ` prefix.\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "asmaul-husna-api.vercel.app",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Asmaul Husna API",
	Description:      "Asmaul Husna API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
