// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/models/requests/asmaul_husna_request.proto

package requests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllAsmaulHusnaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllAsmaulHusnaRequest) Reset() {
	*x = AllAsmaulHusnaRequest{}
	mi := &file_pkg_models_requests_asmaul_husna_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllAsmaulHusnaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllAsmaulHusnaRequest) ProtoMessage() {}

func (x *AllAsmaulHusnaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_requests_asmaul_husna_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllAsmaulHusnaRequest.ProtoReflect.Descriptor instead.
func (*AllAsmaulHusnaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_models_requests_asmaul_husna_request_proto_rawDescGZIP(), []int{0}
}

func (x *AllAsmaulHusnaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AllAsmaulHusnaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_pkg_models_requests_asmaul_husna_request_proto protoreflect.FileDescriptor

const file_pkg_models_requests_asmaul_husna_request_proto_rawDesc = "" +
	"\n" +
	".pkg/models/requests/asmaul_husna_request.proto\x12\brequests\"A\n" +
	"\x15AllAsmaulHusnaRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limitB\"Z asmaul-husna/pkg/models/requestsb\x06proto3"

var (
	file_pkg_models_requests_asmaul_husna_request_proto_rawDescOnce sync.Once
	file_pkg_models_requests_asmaul_husna_request_proto_rawDescData []byte
)

func file_pkg_models_requests_asmaul_husna_request_proto_rawDescGZIP() []byte {
	file_pkg_models_requests_asmaul_husna_request_proto_rawDescOnce.Do(func() {
		file_pkg_models_requests_asmaul_husna_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_models_requests_asmaul_husna_request_proto_rawDesc), len(file_pkg_models_requests_asmaul_husna_request_proto_rawDesc)))
	})
	return file_pkg_models_requests_asmaul_husna_request_proto_rawDescData
}

var file_pkg_models_requests_asmaul_husna_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_models_requests_asmaul_husna_request_proto_goTypes = []any{
	(*AllAsmaulHusnaRequest)(nil), // 0: requests.AllAsmaulHusnaRequest
}
var file_pkg_models_requests_asmaul_husna_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_models_requests_asmaul_husna_request_proto_init() }
func file_pkg_models_requests_asmaul_husna_request_proto_init() {
	if File_pkg_models_requests_asmaul_husna_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_models_requests_asmaul_husna_request_proto_rawDesc), len(file_pkg_models_requests_asmaul_husna_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_models_requests_asmaul_husna_request_proto_goTypes,
		DependencyIndexes: file_pkg_models_requests_asmaul_husna_request_proto_depIdxs,
		MessageInfos:      file_pkg_models_requests_asmaul_husna_request_proto_msgTypes,
	}.Build()
	File_pkg_models_requests_asmaul_husna_request_proto = out.File
	file_pkg_models_requests_asmaul_husna_request_proto_goTypes = nil
	file_pkg_models_requests_asmaul_husna_request_proto_depIdxs = nil
}
